
name: CI

on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
              docker build -t ${{ secrets.DOCKER_USERNAME }}/my-portfolio_v2:${{ github.run_number }} .
              docker build -t ${{ secrets.DOCKER_USERNAME }}/my-portfolio_v2 .

      - name: Push image
        run: |
              echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
              docker push ${{ secrets.REGISTRY_USER }}/my-portfolio_v2:${{ github.run_number }}
              docker push ${{ secrets.REGISTRY_USER }}/my-portfolio_v2